name: Scheduled Run of Main Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run main.py
        run: |
          export TELEGRAM_BOT_API_TOKEN=${{ secrets.TELEGRAM_BOT_API_TOKEN }}
          export TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          uv run python .
          if [ -n "$(git status --porcelain already_notified_datetimes.txt)" ]; then
            CHANGES="true"
          else
            CHANGES="false"
          fi
          # Commit changes to already_notified_datetimes.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add already_notified_datetimes.txt
          git commit -m "Update notified date times" || echo "No changes to commit"
          git push
          if [ "$CHANGES" = "true" ]; then
            exit 1
            # This will trigger the failure of the workflow and will trigger the notification
          fi
